spring:
  application:
    name: zuul-demo
server:
  port: 8801
zuul:
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000
  routes:
    provider-demo:
      path: /provider/**
      serviceId: provider-demo
    consumer-demo:
      path: /consumer/**
      serviceId: consumer-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
provider-demo:
  ribbon:
    ReadTimeout: 60000  # 单位毫秒数
    SocketTimeout: 60000
consumer-demo:
  ribbon:
    ReadTimeout: 60000  # 单位毫秒数
    SocketTimeout: 60000