server:
  port: 8901
spring:
  application:
    name: provider-demo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://192.168.3.101:3306/aemon?useSSL=false
    username: test
    password: test
  redis:
    database: 0
    host: 192.168.3.106
    # password:
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
